global:
  scrape_interval: 15s # How often to check for new numbers

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-backend'
    metrics_path: '/actuator/prometheus' # The URL Spring Boot exposes
    scrape_interval: 5s
    static_configs:
      - targets: ['ebank-backend:8085'] # MUST match container_name and port in compose